version: "3.3"
services:
  mongo:
    image: mongo:4.0.4
    container_name: mongo
    hostname: mongo
    restart: always
    ports:
      - "27017:27017"
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data/mongo:/data/db
      - ./data/mongo/configdb:/data/configdb
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:5.6
    restart: always
    network_mode: host
    ulimits: 
      nproc: 65535
      nofile: 
        soft: 65536
        hard: 65536
      memlock: 
        soft: -1
        hard: -1
    environment:
      - "discovery.type=single-node"
    volumes:
      - ./data/es:/usr/share/elasticsearch/data
      - ./logs/es:/usr/share/elasticsearch/logs
  rasp-cloud:
    container_name: rasp-cloud
    image: zx/rasp-cloud:1.3.7
    restart: always
    network_mode: host
    depends_on:
      - mongo
      - elasticsearch
    volumes:
      - ./conf/rasp:/rasp-cloud/conf
      - ./logs/rasp:/rasp-cloud/logs